// ── Weekly Review Page ────────────────────────────────────────────
// Shows the weekly trading review with performance summary,
// top signals table, and text insights.
// ─────────────────────────────────────────────────────────────────────────────

import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { getWeeklyReview } from "@/domains/trades/functions";
import { useStableServerFn } from "@/shared/hooks/use-stable-server-fn";
import type { WeeklyReview } from "@/domains/trades/weekly-review";
import {
  PageLayout,
  StatsRow,
  SectionTitle,
  EmptyState,
  ScrollArea,
  SkeletonRow,
} from "@/components/vixor/PageLayout";
import { RefreshCw, TrendingUp, TrendingDown, Trophy, AlertTriangle } from "lucide-react";

export const Route = createFileRoute("/_authenticated/review")({
  head: () => ({ meta: [{ title: "Weekly Review — Vixor" }] }),
  component: ReviewPage,
});

// ── Page ─────────────────────────────────────────────────────────────────

function ReviewPage() {
  const fetchReview = useStableServerFn(getWeeklyReview);
  const [autoGenerated, setAutoGenerated] = useState(true);

  const {
    data: review,
    isLoading,
    refetch,
    isFetching,
  } = useQuery({
    queryKey: ["weekly-review"],
    queryFn: () => fetchReview({}),
    staleTime: 5 * 60_000,
    enabled: autoGenerated,
  });

  const handleGenerate = async () => {
    setAutoGenerated(true);
    await refetch();
  };

  const perf = (review as WeeklyReview | undefined)?.performance;
  const topSignals = (review as WeeklyReview | undefined)?.topSignals ?? [];
  const insights = (review as WeeklyReview | undefined)?.insights ?? [];
  const period = (review as WeeklyReview | undefined)?.period;

  const winRateColor = perf
    ? perf.winRate >= 60
      ? "var(--color-bullish)"
      : perf.winRate >= 40
        ? "var(--color-neutral-wait)"
        : "var(--color-bearish)"
    : "var(--color-foreground)";

  return (
    <PageLayout
      title="Weekly Review"
      badge="REVIEW"
      badgeColor="var(--color-primary)"
      loading={isLoading}
      loadingColor="var(--color-primary)"
    >
      {/* ── Period header ──────────────────────────────────────────── */}
      {period && (
        <div
          style={{
            padding: "8px 16px",
            fontSize: "11px",
            color: "var(--color-muted-foreground)",
            borderBottom: `1px solid var(--color-border)`,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <span>
            {new Date(period.from).toLocaleDateString("en-US", {
              month: "short",
              day: "numeric",
            })}
            {" — "}
            {new Date(period.to).toLocaleDateString("en-US", {
              month: "short",
              day: "numeric",
            })}
          </span>
          <button
            onClick={handleGenerate}
            disabled={isFetching}
            style={{
              fontSize: "12px",
              fontWeight: 600,
              color: "var(--color-primary)",
              background: "none",
              border: "none",
              cursor: isFetching ? "wait" : "pointer",
              display: "flex",
              alignItems: "center",
              gap: "4px",
              minHeight: "44px",
            }}
          >
            <RefreshCw
              size={12}
              style={{ animation: isFetching ? "spin 0.7s linear infinite" : "none" }}
            />
            Generate Review
          </button>
        </div>
      )}

      {/* ── Performance Stats ──────────────────────────────────────── */}
      {perf && (
        <StatsRow
          stats={[
            {
              label: "Win Rate",
              value: `${perf.winRate.toFixed(1)}%`,
              icon: "🎯",
              color: winRateColor,
            },
            {
              label: "Profit Factor",
              value: perf.profitFactor === Infinity ? "∞" : `${perf.profitFactor.toFixed(2)}x`,
              icon: "💎",
              color: perf.profitFactor >= 2 ? "var(--color-bullish)" : "var(--color-neutral-wait)",
            },
            {
              label: "Total P&L",
              value: `${perf.totalPnlPct >= 0 ? "+" : ""}${perf.totalPnlPct.toFixed(2)}%`,
              icon: perf.totalPnlPct >= 0 ? "📈" : "📉",
              color: perf.totalPnlPct >= 0 ? "var(--color-bullish)" : "var(--color-bearish)",
            },
            {
              label: "Trades",
              value: String(perf.totalTrades),
              icon: "📊",
              color: "var(--color-foreground)",
              sub:
                perf.byDirection.long.trades > 0 || perf.byDirection.short.trades > 0
                  ? `L:${perf.byDirection.long.trades} S:${perf.byDirection.short.trades}`
                  : undefined,
            },
          ]}
        />
      )}

      <ScrollArea>
        {/* ── Top Signals Table ─────────────────────────────────────── */}
        {topSignals.length > 0 && (
          <>
            <SectionTitle title="Top Signals" count={topSignals.length} />
            {topSignals.map((sig, i) => {
              const isWin = sig.outcome === "WIN";
              const color = isWin ? "var(--color-bullish)" : "var(--color-bearish)";
              return (
                <div
                  key={`${sig.pair}-${i}`}
                  style={{
                    margin: "0 16px 8px",
                    padding: "12px 14px",
                    borderRadius: "12px",
                    background: "var(--color-card)",
                    border: "1px solid var(--color-border)",
                    borderLeft: `3px solid ${color}`,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                  }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                    {isWin ? (
                      <Trophy size={14} style={{ color: "var(--color-bullish)" }} />
                    ) : (
                      <AlertTriangle size={14} style={{ color: "var(--color-bearish)" }} />
                    )}
                    <div>
                      <div
                        style={{
                          fontSize: "13px",
                          fontWeight: 700,
                          color: "var(--color-foreground)",
                          fontFamily: "var(--font-mono)",
                        }}
                      >
                        {sig.pair}
                      </div>
                      <div
                        style={{
                          fontSize: "11px",
                          color: "var(--color-muted-foreground)",
                        }}
                      >
                        {sig.direction}
                      </div>
                    </div>
                  </div>
                  <span
                    style={{
                      fontSize: "14px",
                      fontWeight: 800,
                      fontFamily: "var(--font-mono)",
                      color,
                    }}
                  >
                    {sig.pnlPct >= 0 ? "+" : ""}
                    {sig.pnlPct.toFixed(2)}%
                  </span>
                </div>
              );
            })}
          </>
        )}

        {/* ── Insights Card ────────────────────────────────────────── */}
        {insights.length > 0 && (
          <>
            <SectionTitle title="Insights" count={insights.length} />
            <div
              style={{
                margin: "0 16px 16px",
                padding: "14px 16px",
                borderRadius: "14px",
                background: "color-mix(in srgb, var(--color-primary) 5%, var(--color-card))",
                border:
                  "1px solid color-mix(in srgb, var(--color-primary) 15%, var(--color-border))",
                display: "flex",
                flexDirection: "column",
                gap: "8px",
              }}
            >
              {insights.map((insight, i) => (
                <InsightRow key={i} text={insight} index={i} />
              ))}
            </div>
          </>
        )}

        {/* ── Empty state ──────────────────────────────────────────── */}
        {!isLoading && !review && (
          <EmptyState
            icon="📝"
            title="No Review Yet"
            message={'Click "Generate Review" to create your weekly trading review.'}
          />
        )}
      </ScrollArea>
    </PageLayout>
  );
}

// ── Insight Row ──────────────────────────────────────────────────────────

function InsightRow({ text, index }: { text: string; index: number }) {
  // Determine color based on content
  let bulletColor = "var(--color-foreground)";
  if (text.toLowerCase().includes("profit factor") || text.toLowerCase().includes("win rate")) {
    const numMatch = text.match(/([\d.]+)%/);
    const num = numMatch ? parseFloat(numMatch[1]) : 0;
    bulletColor =
      num >= 50
        ? "var(--color-bullish)"
        : num > 0
          ? "var(--color-neutral-wait)"
          : "var(--color-bearish)";
  } else if (text.toLowerCase().includes("best")) {
    bulletColor = "var(--color-bullish)";
  } else if (text.toLowerCase().includes("losing") || text.toLowerCase().includes("tightening")) {
    bulletColor = "var(--color-bearish)";
  }

  return (
    <div
      style={{
        display: "flex",
        alignItems: "flex-start",
        gap: "8px",
        fontSize: "12px",
        lineHeight: 1.6,
        color: "var(--color-foreground)",
      }}
    >
      <div
        style={{
          width: "6px",
          height: "6px",
          borderRadius: "50%",
          background: bulletColor,
          flexShrink: 0,
          marginTop: "6px",
        }}
      />
      <span>{text}</span>
    </div>
  );
}
