// ============================================================================
// VIXOR Event Consumers — Domain event handlers
// ============================================================================
//
// Registers handlers for emitted domain events.
// Consumers are side-effectful: logging, notifications, cache invalidation.
// They must NEVER mutate domain state directly.
//
// Usage:
//   import { registerEventConsumers } from "@/shared/events/consumers";
//   registerEventConsumers(); // call once at server startup
// ============================================================================

import { VixorEvents } from "./orchestrator";
import type { VixorEventMap } from "./orchestrator";

// ── Signal Transition Consumer ──────────────────────────────────────────────
// Logs structured transition data for observability.
// Future: trigger TanStack Query invalidation, push notifications, analytics.

// ── Journal Auto-Creation on Terminal Transitions ────────────────────────────

/**
 * Calculate outcome metrics for a terminal transition and auto-create
 * a trading journal entry summarizing the trade outcome.
 */
async function autoCreateJournalForTerminalTransition(
  payload: VixorEventMap["signal.transition.completed"],
): Promise<void> {
  try {
    const { supabaseAdmin } = await import("@/shared/supabase/client.server");
    const { ToolRegistry } = await import("@/shared/tool-registry");
    const { VixorEvents } = await import("./orchestrator");

    // Fetch full tracking record for entry/SL/TP prices and timestamps
    const { data: tracking } = await supabaseAdmin
      .from("signal_tracking")
      .select(
        "pair, direction, entry_price, stop_loss, take_profit, activated_at, resolved_at, created_at",
      )
      .eq("id", payload.trackingId)
      .maybeSingle();

    if (!tracking) return;

    const entryPrice = tracking.entry_price ?? 0;
    const direction = tracking.direction as "BUY" | "SELL";
    const dirLabel = direction === "BUY" ? "LONG" : "SHORT";

    // Calculate P&L estimate
    let pnlPct = 0;
    let exitPrice = payload.price ?? 0;

    if (payload.toStatus === "tp3_hit") {
      // Profit: use TP3 price (or last TP in array)
      const tps: number[] = Array.isArray(tracking.take_profit)
        ? (tracking.take_profit as unknown[]).map(Number)
        : [];
      const tp3Price = tps.length >= 3 ? tps[2] : (tps[tps.length - 1] ?? exitPrice);
      exitPrice = tp3Price;
      if (direction === "BUY") {
        pnlPct = entryPrice > 0 ? ((tp3Price - entryPrice) / entryPrice) * 100 : 0;
      } else {
        pnlPct = entryPrice > 0 ? ((entryPrice - tp3Price) / entryPrice) * 100 : 0;
      }
    } else if (payload.toStatus === "sl_hit") {
      // Loss: use SL price
      const slPrice = tracking.stop_loss ?? exitPrice;
      exitPrice = slPrice;
      if (direction === "BUY") {
        pnlPct = entryPrice > 0 ? ((slPrice - entryPrice) / entryPrice) * 100 : 0;
      } else {
        pnlPct = entryPrice > 0 ? ((entryPrice - slPrice) / entryPrice) * 100 : 0;
      }
    }
    // cancelled/expired/invalidated: 0 P&L

    // Calculate duration
    const startAt = tracking.activated_at ?? tracking.created_at;
    const endAt = tracking.resolved_at;
    let durationStr = "N/A";
    if (startAt && endAt) {
      const durationMs = new Date(endAt).getTime() - new Date(startAt).getTime();
      const hours = Math.floor(durationMs / 3_600_000);
      const mins = Math.floor((durationMs % 3_600_000) / 60_000);
      durationStr = hours > 0 ? `${hours}h ${mins}m` : `${mins}m`;
    }

    const pnlSign = pnlPct >= 0 ? "+" : "";
    const outcomeLabel = payload.toStatus === "tp3_hit" ? "TP3 HIT (WIN)" : payload.toStatus;

    // Build journal content
    const content = [
      `**Signal Resolved: ${tracking.pair} ${dirLabel}**`,
      `Outcome: ${outcomeLabel}`,
      `Entry: $${entryPrice.toFixed(2)} → Exit: $${exitPrice.toFixed(2)}`,
      `P&L Estimate: ${pnlSign}${pnlPct.toFixed(2)}%`,
      `Duration: ${durationStr}`,
      `Reason: ${payload.toStatus.replace(/_/g, " ").toUpperCase()}`,
      ``,
      `_Auto-generated by VIXOR signal resolution._`,
    ].join("\n");

    const mood = pnlPct > 0 ? "confident" : pnlPct < 0 ? "cautious" : "neutral";

    // Use ToolRegistry to create the journal entry
    const journalResult = await ToolRegistry.execute(
      "createJournalEntry",
      {
        content,
        pair: tracking.pair,
        mood,
      },
      {
        userId: payload.userId,
        isPremium: false,
        isAdmin: false,
      },
    );

    if (journalResult.success) {
      console.log(
        `[JournalAutoCreate] Created journal entry for terminal signal ${payload.trackingId} (${payload.pair} ${payload.toStatus})`,
      );
    } else {
      console.warn(
        `[JournalAutoCreate] Failed to create journal for ${payload.trackingId}: ${journalResult.error}`,
      );
    }
  } catch (err) {
    // Non-blocking — journal creation should never break the consumer
    console.warn(
      `[JournalAutoCreate] Error creating journal for ${payload.trackingId}:`,
      err instanceof Error ? err.message : String(err),
    );
  }
}

async function handleSignalTransitionCompleted(
  payload: VixorEventMap["signal.transition.completed"],
): Promise<void> {
  const direction = payload.direction === "BUY" ? "LONG" : "SHORT";
  const priceStr = payload.price !== null ? `$${payload.price.toFixed(2)}` : "N/A";
  const tpStr = payload.tpIndex !== null ? ` TP${payload.tpIndex + 1}` : "";

  console.log(
    `[SignalTransition] ${payload.pair} ${direction}: ${payload.fromStatus} → ${payload.toStatus}${tpStr} @ ${priceStr} (actor: ${payload.actor})`,
  );

  // Terminal transition handling: performance metrics + cache invalidation + journal
  const terminalStatuses: string[] = ["tp3_hit", "sl_hit", "cancelled", "expired", "invalidated"];
  if (terminalStatuses.includes(payload.toStatus)) {
    console.log(
      `[SignalTransition] TERMINAL: ${payload.pair} closed as ${payload.toStatus}. trackingId=${payload.trackingId}`,
    );

    // Log performance metrics: duration from activated_at to resolved_at
    try {
      const { supabaseAdmin } = await import("@/shared/supabase/client.server");
      const { data: tracking } = await supabaseAdmin
        .from("signal_tracking")
        .select("activated_at, resolved_at")
        .eq("id", payload.trackingId)
        .maybeSingle();

      if (tracking?.activated_at && tracking?.resolved_at) {
        const durationMs =
          new Date(tracking.resolved_at).getTime() - new Date(tracking.activated_at).getTime();
        const durationMin = (durationMs / 60_000).toFixed(1);
        console.log(
          `[SignalMetrics] ${payload.pair} ${direction} duration: ${durationMin}min (${payload.toStatus})`,
        );
      }
    } catch (err) {
      // Non-blocking — metrics logging should never break the consumer
      console.warn(
        `[SignalMetrics] Failed to fetch tracking for ${payload.trackingId}:`,
        err instanceof Error ? err.message : String(err),
      );
    }

    // Auto-create journal entry for terminal transitions
    void autoCreateJournalForTerminalTransition(payload);

    // Mark TanStack Query cache for invalidation
    console.log(
      `[CacheInvalidation] signalTrackings — triggered by signal.transition.completed (${payload.toStatus})`,
    );
  }
}

// ── Alert Consumer ──────────────────────────────────────────────────────────

async function handleAlertTriggered(payload: VixorEventMap["alert.triggered"]): Promise<void> {
  console.log(
    `[Alert] ${payload.pair} ${payload.condition} triggered — target: $${payload.targetPrice}, current: $${payload.currentPrice}`,
  );

  // Push in-app notification via the notification router
  try {
    const { notificationRouter } = await import("@/shared/notifications");
    void notificationRouter
      .send({
        userId: payload.userId,
        title: `Price Alert: {{pair}}`,
        body: `${payload.pair} ${payload.condition} — Target: $${payload.targetPrice}, Current: $${payload.currentPrice}`,
        severity: "info",
        channels: ["in-app"],
        payload: {
          pair: payload.pair,
          condition: payload.condition,
          targetPrice: payload.targetPrice,
          currentPrice: payload.currentPrice,
          alertId: payload.alertId,
        },
      })
      .catch(() => {
        /* non-blocking */
      });
  } catch {
    // Notification send failure should never break the consumer
  }
}

// ── Analysis Created Consumer ─────────────────────────────────────────────

async function handleAnalysisCreated(payload: VixorEventMap["analysis.created"]): Promise<void> {
  const dirLabel = payload.recommendation === "WAIT" ? "WAIT" : payload.recommendation;
  console.log(
    `[Analysis] ${payload.pair} ${payload.timeframe} — ${dirLabel} (confidence: ${payload.confidence}%, user: ${payload.userId}, analysis: ${payload.analysisId})`,
  );

  // Auto-track: if confidence > 75 and direction is BUY or SELL,
  // emit a signal.tracking.created-like event to wire analysis → signal tracking pipeline
  if (
    payload.confidence > 75 &&
    (payload.recommendation === "BUY" || payload.recommendation === "SELL")
  ) {
    console.log(
      `[Analysis→Signal] High-confidence ${dirLabel} (${payload.confidence}%) — auto-track candidate: ${payload.pair}`,
    );

    // Log the auto-track intent (Phase 6 will wire actual signal tracking creation)
    console.log(
      `[AutoTrack] Would create signal tracking for user=${payload.userId}, pair=${payload.pair}, direction=${payload.recommendation}, analysisId=${payload.analysisId}`,
    );
  }
}

// ── Trade Opened Consumer ──────────────────────────────────────────────────

function handleTradeOpened(payload: VixorEventMap["trade.opened"]): void {
  console.log(
    `[Trade] OPENED ${payload.pair} ${payload.direction.toUpperCase()} @ $${payload.entryPrice} (trade: ${payload.tradeId}, user: ${payload.userId})`,
  );
}

// ── Trade Closed Consumer ──────────────────────────────────────────────────

function handleTradeClosed(payload: VixorEventMap["trade.closed"]): void {
  const pnlSign = payload.pnl >= 0 ? "+" : "";
  const pnlLabel = payload.pnl >= 0 ? "PROFIT" : "LOSS";
  console.log(
    `[Trade] CLOSED ${payload.pair} @ $${payload.exitPrice} — ${pnlLabel} ${pnlSign}$${payload.pnl.toFixed(2)} (trade: ${payload.tradeId})`,
  );
}

// ── Signal Tracking Created Consumer ──────────────────────────────────────

function handleSignalTrackingCreated(payload: VixorEventMap["signal.tracking.created"]): void {
  const dirLabel = payload.direction === "WAIT" ? "WAIT" : payload.direction;
  const slStr = payload.stopLoss ? ` SL: $${payload.stopLoss}` : "";
  console.log(
    `[SignalTracking] CREATED ${payload.pair} ${dirLabel} @ $${payload.entryPrice}${slStr} (tracking: ${payload.trackingId})`,
  );
}

// ── Signal SL Hit Consumer ──────────────────────────────────────────────────

function handleSignalSlHit(payload: VixorEventMap["signal.sl_hit"]): void {
  const direction = payload.direction === "BUY" ? "LONG" : "SHORT";
  console.log(
    `[SignalSL] ${payload.pair} ${direction}: STOP LOSS HIT @ $${payload.currentPrice} (SL was $${payload.stopLoss}, tracking: ${payload.trackingId})`,
  );
}

// ── Signal TP Hit Consumer ──────────────────────────────────────────────────

function handleSignalTpHit(payload: VixorEventMap["signal.tp_hit"]): void {
  const direction = payload.direction === "BUY" ? "LONG" : "SHORT";
  console.log(
    `[SignalTP] ${payload.pair} ${direction}: TP${payload.hitTp} HIT @ $${payload.currentPrice} (tpIndex: ${payload.tpIndex}, tracking: ${payload.trackingId})`,
  );
}

// ── Registration ─────────────────────────────────────────────────────────────

let registered = false;

/**
 * Register all domain event consumers.
 * Safe to call multiple times — only registers once.
 */
export function registerEventConsumers(): void {
  if (registered) return;
  registered = true;

  VixorEvents.on("signal.transition.completed", handleSignalTransitionCompleted);
  VixorEvents.on("alert.triggered", handleAlertTriggered);
  VixorEvents.on("analysis.created", handleAnalysisCreated);
  VixorEvents.on("trade.opened", handleTradeOpened);
  VixorEvents.on("trade.closed", handleTradeClosed);
  VixorEvents.on("signal.tracking.created", handleSignalTrackingCreated);
  VixorEvents.on("signal.tp_hit", handleSignalTpHit);
  VixorEvents.on("signal.sl_hit", handleSignalSlHit);

  console.log(
    "[EventConsumers] Registered signal.transition.completed, alert.triggered, analysis.created, trade.opened, trade.closed, signal.tracking.created, signal.tp_hit, signal.sl_hit",
  );
}

/**
 * Check if event consumers have been registered.
 */
export function isEventConsumersRegistered(): boolean {
  return registered;
}
