// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    // ── Resolve Supabase credentials ──
    // Prefer SUPABASE_ANON_KEY (standard convention) over SUPABASE_PUBLISHABLE_KEY.
    // Trim values to handle accidental whitespace in Vercel env vars.
    const SUPABASE_URL = (process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || "").trim();
    const SUPABASE_ANON_KEY = (
      process.env.SUPABASE_ANON_KEY ||
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.VITE_SUPABASE_ANON_KEY ||
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      ""
    ).trim();

    if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
      const mask = (v: string | undefined) => (v ? `${v.slice(0, 8)}...${v.slice(-4)}` : "(empty)");
      const diag = [
        `S_URL=${mask(process.env.SUPABASE_URL)}`,
        `S_KEY=${mask(process.env.SUPABASE_ANON_KEY)}`,
        `S_PUB=${mask(process.env.SUPABASE_PUBLISHABLE_KEY)}`,
        `V_URL=${mask(process.env.VITE_SUPABASE_URL)}`,
        `V_KEY=${mask(process.env.VITE_SUPABASE_ANON_KEY)}`,
      ].join("|");
      throw new Error(`Missing Supabase env vars [${diag}]`);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    // Create Supabase client WITHOUT setting Authorization in global.headers.
    // We pass the token directly to getUser(token) instead.
    // Setting Authorization in global.headers can conflict with getUser(token)
    // which also sets Authorization, causing "Invalid API key" in some cases.
    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    // Validate the user's JWT — pass token directly, NOT in global headers
    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user) {
      throw new Error(
        `Unauthorized: Invalid token [err:${error?.message}|status:${error?.status}]`,
      );
    }

    const userId = data.user.id;

    // Create a SECOND client with the user's token in global headers
    // for downstream database queries that need RLS user context
    const supabaseAsUser = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: {
        headers: { Authorization: `Bearer ${token}` },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    return next({
      context: {
        supabase: supabaseAsUser,
        userId,
        claims: data.user.app_metadata ?? {},
      },
    });
  },
);
