// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    // ── Resolve Supabase credentials ──
    // Check which env var source actually has a value
    const envSources: Record<string, string | undefined> = {
      SUPABASE_URL: process.env.SUPABASE_URL,
      VITE_SUPABASE_URL: process.env.VITE_SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY: process.env.SUPABASE_PUBLISHABLE_KEY,
      SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
      VITE_SUPABASE_PUBLISHABLE_KEY: process.env.VITE_SUPABASE_PUBLISHABLE_KEY,
      VITE_SUPABASE_ANON_KEY: process.env.VITE_SUPABASE_ANON_KEY,
    };
    // Mask keys for logging (show first 8 + last 4 chars)
    const mask = (v: string | undefined) => (v ? `${v.slice(0, 8)}...${v.slice(-4)}` : "(empty)");

    const SUPABASE_URL = envSources["SUPABASE_URL"] || envSources["VITE_SUPABASE_URL"] || "";
    const SUPABASE_PUBLISHABLE_KEY =
      envSources["SUPABASE_PUBLISHABLE_KEY"] ||
      envSources["SUPABASE_ANON_KEY"] ||
      envSources["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
      envSources["VITE_SUPABASE_ANON_KEY"] ||
      "";

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const diag = Object.entries(envSources)
        .map(([k, v]) => `${k}=${mask(v)}`)
        .join("|");
      const message = `Missing Supabase env vars [${diag}]`;
      console.error(`[Supabase Auth] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    // Use getUser() with the bearer token — this is the most compatible method
    // getClaims() was added in supabase-js v2.149.0 but may not be available in all versions
    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user) {
      const supabaseHost = SUPABASE_URL!.replace(/https?:\/\/(.*?)\.supabase\.co.*/, "$1");
      // Show which env var provided the key, and its masked value
      const keySource = envSources["SUPABASE_PUBLISHABLE_KEY"]
        ? "SUPABASE_PUBLISHABLE_KEY"
        : envSources["SUPABASE_ANON_KEY"]
          ? "SUPABASE_ANON_KEY"
          : envSources["VITE_SUPABASE_PUBLISHABLE_KEY"]
            ? "VITE_SUPABASE_PUBLISHABLE_KEY"
            : "VITE_SUPABASE_ANON_KEY";
      const detail = [
        `key_src:${keySource}`,
        `key_val:${mask(SUPABASE_PUBLISHABLE_KEY)}`,
        `url:${SUPABASE_URL}`,
        `err:${error?.message}|${error?.status}`,
      ].join("|");
      throw new Error(`Unauthorized: Invalid token [${detail}]`);
    }

    const userId = data.user.id;

    return next({
      context: {
        supabase,
        userId,
        claims: data.user.app_metadata ?? {},
      },
    });
  },
);
