// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  // Support both naming conventions: SUPABASE_ANON_KEY (common) and SUPABASE_PUBLISHABLE_KEY (TanStack Start default)
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY / SUPABASE_ANON_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}.`;
    console.warn(`[Supabase] ${message} — client will be non-functional until env vars are set.`);
    // Return a dummy client that won't crash SSR, but won't work either
    // The user will be redirected to /auth and then see the login page
    // Once the client-side JS hydrates with proper env vars, it will work
    return null as unknown as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _initAttempted = false;

// Import the supabase client like this:
// import { supabase } from "@/shared/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase && !_initAttempted) {
      _initAttempted = true;
      try {
        _supabase = createSupabaseClient();
      } catch (e) {
        console.error("[Supabase] Failed to create client:", e);
      }
    }
    if (_supabase) {
      return Reflect.get(_supabase, prop, receiver);
    }
    // Return a no-op function for any method calls when client is not available
    return () => Promise.resolve({ data: null, error: new Error("Supabase not configured") });
  },
});
