// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    try {
      const { data } = await supabase.auth.getSession()
      const token = data.session?.access_token
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
    } catch (error) {
      // If Supabase client is not configured (missing env vars),
      // proceed without auth headers — the server middleware will
      // return an appropriate error to the client.
      console.warn('[Supabase Auth Attacher] Failed to get session:', error instanceof Error ? error.message : String(error))
      return next({
        headers: {},
      })
    }
  },
)
